# Generated by Django 3.2.25 on 2025-06-08 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(upload_to='poetas/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('enlace2', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
