# Generated by Django 3.2.25 on 2025-06-10 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_delete_ttpd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('nacionalidad', models.TextField()),
                ('nacimiento', models.DateField()),
                ('ocupacion', models.TextField()),
                ('cantidad_albumes', models.TextField()),
                ('cantidad_canciones', models.TextField()),
                ('exitos_musicales', models.TextField()),
                ('nominaciones', models.TextField()),
                ('premios', models.TextField()),
                ('letras', models.TextField()),
                ('hate', models.TextField()),
                ('mejor_album', models.TextField()),
                ('peor_album', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
