# Generated by Django 3.2.25 on 2025-06-10 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_ttpd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TTPD',
            new_name='Publicacion_2',
        ),
    ]
