# Generated by Django 3.2.25 on 2025-06-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20250617_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumes',
            old_name='nacionalidad',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='albumes',
            old_name='nacimiento',
            new_name='lanzamiento',
        ),
        migrations.RemoveField(
            model_name='albumes',
            name='entidad',
        ),
    ]
