# Generated by Django 3.2.25 on 2025-06-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20250617_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumes',
            old_name='cantidad_albumes',
            new_name='canciones',
        ),
        migrations.RenameField(
            model_name='albumes',
            old_name='cantidad_canciones',
            new_name='duracion_album',
        ),
        migrations.RenameField(
            model_name='albumes',
            old_name='criticas',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='albumes',
            old_name='exitos_musicales',
            new_name='reproducciones_diarias',
        ),
        migrations.RemoveField(
            model_name='albumes',
            name='letras',
        ),
        migrations.RemoveField(
            model_name='albumes',
            name='mejor_album',
        ),
        migrations.RemoveField(
            model_name='albumes',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='albumes',
            name='peor_album',
        ),
    ]
