# Generated by Django 3.2.25 on 2025-06-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250617_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumes',
            old_name='nominaciones',
            new_name='reconocimiento',
        ),
        migrations.RemoveField(
            model_name='albumes',
            name='premios',
        ),
    ]
