# Generated by Django 3.2.25 on 2025-06-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20250617_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumes',
            name='otro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumes',
            name='premio_grammy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumes',
            name='productores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumes',
            name='resena_personal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
