# Generated by Django 3.2.25 on 2025-06-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20250617_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumes',
            name='productores',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='albumes',
            name='resena_personal',
            field=models.TextField(),
        ),
    ]
