# Generated by Django 3.2.25 on 2025-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20250617_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumes',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
