# Generated by Django 3.2.25 on 2025-06-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_albumes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumes',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
